### ISSUE TITLE
运行 track_predict.py 时显示缺少文件 yolo_anchors.txt

### ISSUE THREAD

**Issue by ballista1704** [yzqxy/yolov5_obb_prune_tracking#7]
运行目标跟踪的时候，程序会报告以下文件（yolo_anchors.txt）不存在：  
```
Traceback (most recent call last):
  File "/run/media/cv/e/zzy/yolov5_obb_prune_tracking-master/track_predict.py", line 90, in <module>
    detector = Detector()
  File "/run/media/cv/e/zzy/yolov5_obb_prune_tracking-master/YoloDeepSort/AIDetector.py", line 94, in __init__
    self.anchors, self.num_anchors      = get_anchors(self.anchors_path)
  File "/run/media/cv/e/zzy/yolov5_obb_prune_tracking-master/YoloDeepSort/yolov7/utils/utils.py", line 53, in get_anchors
    with open(anchors_path, encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'YoloDeepSort/yolov7/model_data/yolo_anchors.txt'
```
yolo_anchors.txt 的内容应该是什么？能否直接使用原版 yolov7 默认的 anchors？

**Comment by sjx3906** [comment]
朋友请问你解决了吗

**Comment by ballista1704** [comment]
@sjx3906   
把 YoloDeepSort/AIDetector.py 里面第 94、95 行注释掉。  
![image](https://github.com/yzqxy/yolov5_obb_prune_tracking/assets/80738608/3d4f2041-aa80-4893-b835-74982852b9b9)
这个办法能在 inference 的时候起效，不知道训练的时候可不可行。
